[project]
name = "token-trace"
version = "0.1.0"
description = "Transformer token flow visualizer"
authors = [
    { name = "Seongho Son, Liza Karmannaya, Daniel Tan, David Chanin", email = "chanindav@gmail.com" },
]
dependencies = [
    "transformers>=4.39.3",
    "transformer-lens>=1.15.0",
    "sae-lens>=0.2.0",
    "pandera>=0.18.3",
]
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
client = [
    "streamlit>=1.33.0",
    "st-annotated-text>=4.0.1",
    "pytest>=8.1.1",
]
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=8.1.1",
    "ruff>=0.3.3",
    "pyright>=1.1.354",
    "notebook>=7.1.2",
]

[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeStubs = "none"
reportUnknownMemberType = "none"
reportUnknownArgumentType = "none"
reportUnknownVariableType = "none"
reportUntypedFunctionDecorator = "none"
reportUnnecessaryIsInstance = "none"
reportUnnecessaryComparison = "none"
reportConstantRedefinition = "none"
reportUnknownLambdaType = "none"

[tool.isort]
profile = "black"

[tool.ruff]
exclude = ["dist", "docs"]

[tool.ruff.lint]
ignore = ["E203", "E501", "E731"]
extend-select = ["UP", "TID", "I", "F", "E", "ARG"]

[tool.pdm.scripts]
run_app = "streamlit run app/token_trace_app.py"